#include <stdio.h>

int main() _{
  // Create Variables
  int myNum = 5;                                 // Integer
 (Whole number)
   float myFloatnum 5.99;                       //  Floating
  point number
   char myLetter = 'D';                        //  Character

   // print variables
   printf("%d\n", myNum);
   printf("%f\n", myFloatNum);
   printf("%c\n", myLetter);
   return 0;
}